version: "3"

tasks:
  setgenfiles:
    aliases:
      - set-gen
      - stg
    desc: "Sets gen folders"
    cmds:
      - mkdir -p ./gen/python
      - mkdir -p ./gen/python/tus
      - mkdir -p ./gen/python/mobile_bank
      - mkdir -p ./gen/python/cards
      - mkdir -p ./gen/python/card_prices
      - mkdir -p ./gen/python/reports
      - mkdir -p ./gen/python/accountant
      - mkdir -p ./gen/python/upload_file
      - mkdir -p ./gen/python/application
      - mkdir -p ./gen/python/poll
      - mkdir -p ./gen/go
      - mkdir -p ./gen/go/tus
      - mkdir -p ./gen/go/mobile_bank
      - mkdir -p ./gen/go/cards
      - mkdir -p ./gen/go/card_prices
      - mkdir -p ./gen/go/reports
      - mkdir -p ./gen/go/accountant
      - mkdir -p ./gen/go/upload_file
      - mkdir -p ./gen/go/application
      - mkdir -p ./gen/go/poll

  generatetus:
    aliases:
      - gen-tus
    desc: "Generate Python code from tus proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/tus/ --grpc_python_out=./gen/python/tus/ proto/tus.proto

  generatemobilebank:
    aliases:
      - gen-mob
      - gen-mbank
    desc: "Generate Python code from mobile bank proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/mobile_bank/ --grpc_python_out=./gen/python/mobile_bank/ proto/mobile_bank.proto

  generatecards:
    aliases:
      - gen-cards
    desc: "Generate Python code from cards proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/cards/ --grpc_python_out=./gen/python/cards/ proto/cards.proto

  generatecardprices:
    aliases:
      - gen-prices
      - gen-cprices
    desc: "Generate Python code from card prices proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/card_prices/ --grpc_python_out=./gen/python/card_prices/ proto/card_prices.proto

  generatereports:
    aliases:
      - gen-rep
    desc: "Generate Python code from reports proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/reports/ --grpc_python_out=./gen/python/reports/ proto/reports.proto

  generateaccountant:
    aliases:
      - gen-acc
    desc: "Generate Python code from accountants proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/accountant/ --grpc_python_out=./gen/python/accountant/ proto/accountant.proto

  generatesavefile:
    aliases:
      - gen-save-file
    desc: "Generate Python code from save file proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/upload_file/ --grpc_python_out=./gen/python/upload_file/ proto/upload_file.proto

  generateapplication:
    aliases:
      - gen-app
    desc: "Generate Python code from applications proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/application/ --grpc_python_out=./gen/python/application/ proto/application.proto

  generatepoll:
    aliases:
      - gen-poll
    desc: "Generate Python code from polls proto files"
    cmds:
      - python -m grpc_tools.protoc -I=proto --python_out=./gen/python/poll/ --grpc_python_out=./gen/python/poll/ proto/poll.proto

  generatetus-go:
    aliases:
      - gen-tus-go
    desc: "Generate Go code from tus proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/tus/ --go-grpc_out=./gen/go/tus/ proto/tus.proto

  generatemobilebank-go:
    aliases:
      - gen-mob-go
      - gen-mbank-go
    desc: "Generate Go code from mobile bank proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/mobile_bank/ --go-grpc_out=./gen/go/mobile_bank/ proto/mobile_bank.proto

  generatecards-go:
    aliases:
      - gen-cards-go
    desc: "Generate Go code from cards proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/cards/ --go-grpc_out=./gen/go/cards/ proto/cards.proto

  generatecardprices-go:
    aliases:
      - gen-prices-go
      - gen-cprices-go
    desc: "Generate Go code from card prices proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/card_prices/ --go-grpc_out=./gen/go/card_prices/ proto/card_prices.proto

  generatereports-go:
    aliases:
      - gen-rep-go
    desc: "Generate go code from reports proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/reports/ --go-grpc_out=./gen/go/reports/ proto/reports.proto

  generateaccountant-go:
    aliases:
      - gen-acc-go
    desc: "Generate go code from accountants proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/accountant/ --go-grpc_out=./gen/go/accountant/ proto/accountant.proto

  generateapplication-go:
    aliases:
      - gen-acc-go
    desc: "Generate go code from applications proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/application/ --go-grpc_out=./gen/go/application/ proto/application.proto

  generatepoll-go:
    aliases:
      - gen-poll-go
    desc: "Generate go code from poll proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/poll/ --go-grpc_out=./gen/go/poll/ proto/poll.proto

  generatesavefile-go:
    aliases:
      - gen-save-file-go
    desc: "Generate go code from save file proto files"
    cmds:
      - protoc -I=proto --go_out=./gen/go/upload_file/ --go-grpc_out=./gen/go/upload_file/ proto/upload_file.proto

  generate-all:
    desc: "Generate all proto files for both Python and Go"
    deps:
      - setgenfiles
      - generatetus
      - generatemobilebank
      - generatecards
      - generatecardprices
      - generatereports
      - generateaccountant
      - generatesavefile
      - generateapplication
      - generatepoll
      - generatetus-go
      - generatemobilebank-go
      - generatecards-go
      - generatecardprices-go
      - generatereports-go
      - generateaccountant-go
      - generatesavefile-go
      - generateapplication-go
      - generatepoll-go
